# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "active_configuration"
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Mango"]
  s.date = "2013-07-07"
  s.description = "ActiveConfiguration is an engine that exposes a generic settings store to \n                       ActiveRecord models. Made for very configurable applications, it allows you \n                       to avoid implementing specific ways to store settings for each model that \n                       needs such configuration. If your application isn't very configurable, \n                       ActiveConfiguration is probably overkill."
  s.email = "tsmango@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "app/models/active_configuration/setting.rb",
    "lib/active_configuration.rb",
    "lib/active_configuration/base.rb",
    "lib/active_configuration/engine.rb",
    "lib/active_configuration/error.rb",
    "lib/active_configuration/option.rb",
    "lib/active_configuration/setting_manager.rb",
    "lib/active_configuration/setting_proxy.rb",
    "lib/active_configuration/table_name.rb",
    "lib/active_configuration/version.rb",
    "lib/active_record/configuration.rb",
    "lib/generators/active_configuration/install/install_generator.rb",
    "lib/generators/active_configuration/install/templates/create_active_configuration_settings.rb"
  ]
  s.homepage = "http://github.com/tsmango/active_configuration"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A generic settings store for Rails 3.x and 4.x ActiveRecord models."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<active_configuration>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<active_configuration>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<active_configuration>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
  end
end

